version: 2

updates:
  - commit-message:
      prefix: "chore"
    directory: "/"
    package-ecosystem: "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
      - "release: patch"
    schedule:
      day: "monday"
      interval: "weekly"
    target-branch: "main"

  - commit-message:
      prefix: "chore"
    directory: "/"
    package-ecosystem: "npm"
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    labels:
      - "dependencies"
      - "npm"
      - "release: patch"
    schedule:
      day: "monday"
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: "increase"
