"""Deterministic glue for the codex-review:adopt capability.

Composes the workflow + starter reference-file + ADOPTION report. Refuses to
write any artifact unless every CC-NN invariant passes against the emitted
workflow.

Invoked from the capability prompt as:

    python3 scripts/adopt.py --target-repo /path/to/repo [--allow-users ...] [--write]

The default is dry-run; pass --write to land the three artifacts in the
target repository's working tree.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

from lib.detect import DetectOptions, Language, detect, make_filesystem_reader
from lib.invariants import assert_workflow, format_report
from lib.pin_resolver import GhExec, PinResolution, default_gh, resolve_pin
from lib.reference_layerer import LayerOptions, layer_reference
from lib.workflow_templates import WorkflowTemplateOptions, render_hardened_workflow

DEFAULT_DEFAULTS_PATH = "defaults/review-reference.md"


class AdoptError(Exception):
    """Raised when adopt cannot complete (pin resolution failed, invariants failed, etc.)."""


@dataclass(frozen=True)
class AdoptInputs:
    allow_users: str = ""
    dry_run: bool = True
    pin: PinResolution | None = None
    project_name: str | None = None
    target_repo: str | None = None


@dataclass(frozen=True)
class WriteEntry:
    content: str
    path: str


@dataclass(frozen=True)
class AdoptOutputs:
    adoption_report: str
    invariants_report: str
    reference_file: str
    workflow: str
    writes: tuple[WriteEntry, ...]


@dataclass(frozen=True)
class _BareActionResult:
    found: bool
    locations: tuple[str, ...] = ()


def _pick_project_name(target_repo: str, override: str | None) -> str:
    if override is not None and override:
        return override
    parts = [part for part in target_repo.split("/") if part]
    return parts[-1] if parts else "repo"


def _detect_bare_action(target_repo: Path) -> _BareActionResult:
    workflows_dir = target_repo / ".github" / "workflows"
    if not workflows_dir.is_dir():
        return _BareActionResult(found=False)
    locations: list[str] = []
    import re

    pattern = re.compile(r"milanhorvatovic/codex-ai-code-review-action@[0-9a-f]{40}")
    for path in sorted(workflows_dir.iterdir()):
        if not path.is_file():
            continue
        if not path.name.endswith((".yaml", ".yml")):
            continue
        if pattern.search(path.read_text(encoding="utf-8")):
            locations.append(f".github/workflows/{path.name}")
    return _BareActionResult(found=bool(locations), locations=tuple(locations))


def _load_defaults_reference(target_repo: Path) -> str:
    candidates = [target_repo / DEFAULT_DEFAULTS_PATH, target_repo.parent / DEFAULT_DEFAULTS_PATH]
    for candidate in candidates:
        if candidate.exists():
            return candidate.read_text(encoding="utf-8")
    raise AdoptError(
        f"could not locate {DEFAULT_DEFAULTS_PATH} relative to target-repo; pass an absolute path or run from a checkout that has the action's defaults available"
    )


@dataclass
class _ReportContext:
    allow_users: str
    bare_action: _BareActionResult
    facts: object
    invariants_report: str
    pin: PinResolution
    project_name: str


def _render_adoption_report(ctx: _ReportContext) -> str:
    facts = ctx.facts  # type: ignore[assignment]
    languages = ", ".join(getattr(facts, "languages", ())) or "(none detected)"
    package_managers = ", ".join(getattr(facts, "package_managers", ())) or "(none)"
    ci_provider = getattr(facts, "ci_provider", "none")
    has_existing = getattr(facts, "has_codex_review_workflow", False)

    lines: list[str] = []
    lines.append(f"# Adoption report — {ctx.project_name}")
    lines.append("")
    lines.append("> Generated by `codex-review:adopt`. Review before committing.")
    lines.append("")
    lines.append("## Resolved pin")
    lines.append("")
    lines.append(f"- Tag: `{ctx.pin.tag}`")
    lines.append(f"- SHA: `{ctx.pin.sha}`")
    lines.append("")
    lines.append("## Detection summary")
    lines.append("")
    lines.append(f"- Languages: {languages}")
    lines.append(f"- Package managers: {package_managers}")
    lines.append(f"- CI provider: {ci_provider}")
    existing_marker = "yes (will overwrite on dry-run: false)" if has_existing else "no"
    lines.append(f"- Existing codex-review workflow: {existing_marker}")
    lines.append("")
    if ctx.bare_action.found:
        lines.append("## Bare-action remediation")
        lines.append("")
        lines.append("The following workflow files reference the bare action and must be rewritten to the three sub-actions:")
        for location in ctx.bare_action.locations:
            lines.append(f"- `{location}`")
        lines.append("")
    lines.append("## Decisions and consumer-controls invariants")
    lines.append("")
    lines.append(f"- `allow-users`: `{ctx.allow_users or '(empty)'}` — scopes who can trigger the prepare step.")
    lines.append("- Trigger: `pull_request` (CC-02).")
    lines.append("- Same-repo gate on every job: yes (CC-03).")
    lines.append("- Environment scoping for `OPENAI_API_KEY`: `codex-review` on the review job only (CC-04).")
    lines.append("- `prepare`/`review` permissions: `contents: read` only (CC-05).")
    lines.append("- `publish` permissions: `contents: read` + `pull-requests: write` (CC-06).")
    lines.append('- `retain-findings`: `"false"` explicit (CC-07).')
    lines.append('- `fail-on-missing-chunks`: `"true"` (CC-08; assumes pinned action ≥ v2.1.0).')
    lines.append("- `review-reference-file`: NOT wired into the workflow (CC-09; starter file emitted but unwired pending issue #97).")
    lines.append("")
    lines.append("## Invariants assertion result")
    lines.append("")
    lines.append("```")
    lines.append(ctx.invariants_report)
    lines.append("```")
    lines.append("")
    lines.append("## Open question")
    lines.append("")
    lines.append(
        "If your repository explicitly accepts that same-repo PR authors can edit `.github/codex/review-reference.md` and steer the review prompt of their own PR, you can wire the file by adding a `# workspace-mode accepted by ...` comment on the prepare step's `with:` block and the `review-reference-file: .github/codex/review-reference.md` line. Otherwise wait for [issue #97](https://github.com/milanhorvatovic/codex-ai-code-review-action/issues/97)."
    )
    lines.append("")
    return "\n".join(lines)


def run_adopt(inputs: AdoptInputs, gh: GhExec | None = None) -> AdoptOutputs:
    target_repo_str = inputs.target_repo or str(Path.cwd())
    target_repo = Path(target_repo_str)
    pin = inputs.pin if inputs.pin is not None else resolve_pin(gh or default_gh())
    project_name = _pick_project_name(target_repo_str, inputs.project_name)

    reader = make_filesystem_reader(str(target_repo))
    facts = detect(reader, DetectOptions())
    bare_action = _detect_bare_action(target_repo)

    workflow = render_hardened_workflow(
        WorkflowTemplateOptions(allow_users=inputs.allow_users, pin_sha=pin.sha, pin_tag=pin.tag)
    )
    report = assert_workflow(workflow, action_version=pin.tag)
    if not report.ok:
        raise AdoptError(
            "emitted workflow failed consumer-controls invariants:\n" + format_report(report)
        )

    languages: tuple[Language, ...] = facts.languages or ("javascript",)
    reference_file = layer_reference(
        _load_defaults_reference(target_repo),
        LayerOptions(languages=languages, project_name=project_name),
    )

    invariants_report = format_report(report)
    adoption_report = _render_adoption_report(
        _ReportContext(
            allow_users=inputs.allow_users,
            bare_action=bare_action,
            facts=facts,
            invariants_report=invariants_report,
            pin=pin,
            project_name=project_name,
        )
    )

    writes = (
        WriteEntry(content=workflow, path=".github/workflows/codex-review.yaml"),
        WriteEntry(content=reference_file, path=".github/codex/review-reference.md"),
        WriteEntry(content=adoption_report, path="ADOPTION.md"),
    )

    if not inputs.dry_run:
        for entry in writes:
            destination = target_repo / entry.path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(entry.content, encoding="utf-8")

    return AdoptOutputs(
        adoption_report=adoption_report,
        invariants_report=invariants_report,
        reference_file=reference_file,
        workflow=workflow,
        writes=writes,
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="adopt.py",
        description="Generate a hardened codex-review workflow + starter review-reference + ADOPTION report.",
    )
    parser.add_argument(
        "--target-repo",
        default=".",
        help="Path to the consumer's repository checkout (default: current directory).",
    )
    parser.add_argument(
        "--allow-users",
        default="",
        help="Comma-separated GitHub usernames for the prepare allowlist. Empty allows all same-repo PR authors.",
    )
    parser.add_argument(
        "--project-name",
        default=None,
        help="Project name shown in the starter reference file (default: target-repo's last path segment).",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write artifacts to the target repository's working tree. Default is dry-run.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    inputs = AdoptInputs(
        allow_users=args.allow_users,
        dry_run=not args.write,
        project_name=args.project_name,
        target_repo=args.target_repo,
    )
    try:
        out = run_adopt(inputs)
    except AdoptError as exc:
        print(f"adopt failed: {exc}", file=sys.stderr)
        return 1
    if args.write:
        print(f"Wrote {len(out.writes)} artifact(s) under {Path(args.target_repo).resolve()}.")
    else:
        print("# === Workflow ===")
        print(out.workflow)
        print("# === Starter reference ===")
        print(out.reference_file)
        print("# === ADOPTION report ===")
        print(out.adoption_report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
