"""Layer a starter review-reference.md against defaults/review-reference.md.

Section selection only — pick language-specific blocks plus a fixed set of
always-include blocks (YAML, Markdown, Dockerfile). No few-shot synthesis in
v0; that would couple the skill to model temperature and break goldens.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from .detect import Language

_HEADING_RE = re.compile(r"^### ([^(\n]+?)(?:\s*\(`?(.+?)`?\))?$", re.MULTILINE)

_LANG_TO_HEADING: dict[Language, tuple[str, ...]] = {
    "go": ("Go",),
    "java": ("Java / Kotlin",),
    "javascript": ("JavaScript / TypeScript",),
    "kotlin": ("Java / Kotlin",),
    "php": (),
    "python": ("Python",),
    "ruby": (),
    "rust": ("Rust",),
    "shell": ("Shell scripts",),
    "typescript": ("JavaScript / TypeScript",),
}

_ALWAYS_INCLUDE: tuple[str, ...] = ("YAML / Configuration", "Markdown", "Dockerfile / Container")


@dataclass(frozen=True)
class Section:
    end: int
    heading: str
    start: int


def list_sections(reference: str) -> tuple[Section, ...]:
    matches = list(_HEADING_RE.finditer(reference))
    sections: list[Section] = []
    for index, match in enumerate(matches):
        heading = match.group(1).strip()
        start = match.start()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(reference)
        sections.append(Section(end=end, heading=heading, start=start))
    return tuple(sections)


def pick_sections_for_languages(reference: str, languages: tuple[Language, ...]) -> tuple[Section, ...]:
    wanted: set[str] = set()
    for language in languages:
        for heading in _LANG_TO_HEADING.get(language, ()):
            wanted.add(heading)
    for heading in _ALWAYS_INCLUDE:
        wanted.add(heading)

    chosen: list[Section] = []
    for section in list_sections(reference):
        for candidate in wanted:
            if section.heading.startswith(candidate):
                chosen.append(section)
                break
    return tuple(chosen)


@dataclass(frozen=True)
class LayerOptions:
    languages: tuple[Language, ...]
    project_name: str


_HEADER_TEMPLATE = """# Review reference — {project_name}

<!--
  Generated by codex-review:adopt. Customize the sections below to fit your repo's review priorities.
  This file is NOT wired into the workflow's `with: review-reference-file:` block by default.
  Workspace-mode reads expose policy edits to PR authors. Wire the file only after either:
  (a) deciding to accept workspace-mode posture for same-repo PRs (document the consent inline), or
  (b) issue #97 lands review-reference-source: base, at which point this default flips.
-->

## Focus areas

Evaluate the pull request diff for:

1. **Correctness** — behavioral bugs, regressions, logic errors
2. **Security** — injection, secret exposure, unsafe input handling
3. **Performance** — unnecessary allocations, O(n^2) where O(n) suffices
4. **Maintainability** — readability, naming, duplication, unnecessary complexity
5. **Test coverage** — risky changes without corresponding tests

## File-type review guidance

Apply the appropriate checklist for each file type changed in the diff."""


def layer_reference(defaults_content: str, options: LayerOptions) -> str:
    sections = pick_sections_for_languages(defaults_content, options.languages)
    blocks = "\n\n".join(defaults_content[section.start : section.end].rstrip() for section in sections)
    header = _HEADER_TEMPLATE.format(project_name=options.project_name)
    return f"{header}\n\n{blocks}\n"
