import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";

import { detect, type RepoFacts, type Language } from "../../lib/detect.js";
import { assertWorkflow, formatReport } from "../../lib/invariants.js";
import { resolvePin, type GhExec, type PinResolution } from "../../lib/pin-resolver.js";
import { layerReference } from "../../lib/reference-layerer.js";
import { renderHardenedWorkflow } from "../../lib/workflow-templates.js";

export type AdoptInputs = {
  allowUsers?: string;
  dryRun?: boolean;
  pin?: PinResolution;
  projectName?: string;
  targetRepo?: string;
};

export type AdoptOutputs = {
  adoptionReport: string;
  invariantsReport: string;
  referenceFile: string;
  workflow: string;
  writes: ReadonlyArray<{ content: string; path: string }>;
};

export class AdoptError extends Error {
  override name = "AdoptError";
}

const DEFAULT_DEFAULTS_PATH = "defaults/review-reference.md";

function makeRepoReader(root: string): {
  exists: (path: string) => boolean;
  listFiles: (dir: string) => ReadonlyArray<string>;
  readFile: (path: string) => string;
} {
  return {
    exists: (path) => existsSync(resolve(root, path)),
    listFiles: (dir) => {
      try {
        return readdirSync(resolve(root, dir));
      } catch {
        return [];
      }
    },
    readFile: (path) => readFileSync(resolve(root, path), "utf-8"),
  };
}

function defaultGh(): GhExec {
  return (args) => {
    const result = spawnSync("gh", args, { encoding: "utf-8" });
    return {
      code: result.status ?? 1,
      stderr: result.stderr ?? "",
      stdout: result.stdout ?? "",
    };
  };
}

function pickProjectName(targetRepo: string, override: string | undefined): string {
  if (override !== undefined && override.length > 0) return override;
  const segments = targetRepo.split("/").filter((s) => s.length > 0);
  return segments[segments.length - 1] ?? "repo";
}

function detectBareAction(targetRepo: string): { found: boolean; locations: ReadonlyArray<string> } {
  const workflowsDir = resolve(targetRepo, ".github/workflows");
  if (!existsSync(workflowsDir)) return { found: false, locations: [] };
  const locations: string[] = [];
  for (const file of readdirSync(workflowsDir)) {
    const path = resolve(workflowsDir, file);
    try {
      if (!statSync(path).isFile()) continue;
    } catch {
      continue;
    }
    if (!/\.ya?ml$/.test(file)) continue;
    const text = readFileSync(path, "utf-8");
    if (/milanhorvatovic\/codex-ai-code-review-action@[0-9a-f]{40}/.test(text)) {
      locations.push(`.github/workflows/${file}`);
    }
  }
  return { found: locations.length > 0, locations };
}

function loadDefaultsReference(targetRepo: string): string {
  const candidates = [
    resolve(targetRepo, DEFAULT_DEFAULTS_PATH),
    resolve(targetRepo, "..", DEFAULT_DEFAULTS_PATH),
  ];
  for (const path of candidates) {
    if (existsSync(path)) return readFileSync(path, "utf-8");
  }
  throw new AdoptError(
    `could not locate ${DEFAULT_DEFAULTS_PATH} relative to target-repo; pass an absolute path or run from a checkout that has the action's defaults available`,
  );
}

function renderAdoptionReport(args: {
  allowUsers: string;
  bareAction: { found: boolean; locations: ReadonlyArray<string> };
  facts: RepoFacts;
  invariantsReport: string;
  pin: PinResolution;
  projectName: string;
}): string {
  const lines: string[] = [];
  lines.push(`# Adoption report — ${args.projectName}`);
  lines.push("");
  lines.push("> Generated by `codex-review:adopt`. Review before committing.");
  lines.push("");
  lines.push("## Resolved pin");
  lines.push("");
  lines.push(`- Tag: \`${args.pin.tag}\``);
  lines.push(`- SHA: \`${args.pin.sha}\``);
  lines.push("");
  lines.push("## Detection summary");
  lines.push("");
  lines.push(`- Languages: ${args.facts.languages.join(", ") || "(none detected)"}`);
  lines.push(`- Package managers: ${args.facts.packageManagers.join(", ") || "(none)"}`);
  lines.push(`- CI provider: ${args.facts.ciProvider}`);
  lines.push(`- Existing codex-review workflow: ${args.facts.hasCodexReviewWorkflow ? "yes (will overwrite on dry-run: false)" : "no"}`);
  lines.push("");
  if (args.bareAction.found) {
    lines.push("## Bare-action remediation");
    lines.push("");
    lines.push("The following workflow files reference the bare action and must be rewritten to the three sub-actions:");
    for (const loc of args.bareAction.locations) lines.push(`- \`${loc}\``);
    lines.push("");
  }
  lines.push("## Decisions and consumer-controls invariants");
  lines.push("");
  lines.push(`- \`allow-users\`: \`${args.allowUsers || "(empty)"}\` — scopes who can trigger the prepare step.`);
  lines.push("- Trigger: `pull_request` (CC-02).");
  lines.push("- Same-repo gate on every job: yes (CC-03).");
  lines.push("- Environment scoping for `OPENAI_API_KEY`: `codex-review` on the review job only (CC-04).");
  lines.push("- `prepare`/`review` permissions: `contents: read` only (CC-05).");
  lines.push("- `publish` permissions: `contents: read` + `pull-requests: write` (CC-06).");
  lines.push("- `retain-findings`: `\"false\"` explicit (CC-07).");
  lines.push("- `fail-on-missing-chunks`: `\"true\"` (CC-08; assumes pinned action ≥ v2.1.0).");
  lines.push("- `review-reference-file`: NOT wired into the workflow (CC-09; starter file emitted but unwired pending issue #97).");
  lines.push("");
  lines.push("## Invariants assertion result");
  lines.push("");
  lines.push("```");
  lines.push(args.invariantsReport);
  lines.push("```");
  lines.push("");
  lines.push("## Open question");
  lines.push("");
  lines.push("If your repository explicitly accepts that same-repo PR authors can edit `.github/codex/review-reference.md` and steer the review prompt of their own PR, you can wire the file by adding a `# workspace-mode accepted by ...` comment on the prepare step's `with:` block and the `review-reference-file: .github/codex/review-reference.md` line. Otherwise wait for [issue #97](https://github.com/milanhorvatovic/codex-ai-code-review-action/issues/97).");
  lines.push("");
  return lines.join("\n");
}

export function runAdopt(inputs: AdoptInputs, gh: GhExec = defaultGh()): AdoptOutputs {
  const targetRepo = inputs.targetRepo ?? process.cwd();
  const allowUsers = inputs.allowUsers ?? "";
  const dryRun = inputs.dryRun ?? true;
  const pin = inputs.pin ?? resolvePin(gh);
  const projectName = pickProjectName(targetRepo, inputs.projectName);

  const reader = makeRepoReader(targetRepo);
  const facts = detect(reader);
  const bareAction = detectBareAction(targetRepo);

  const workflow = renderHardenedWorkflow({ allowUsers, pinSha: pin.sha, pinTag: pin.tag });
  const report = assertWorkflow(workflow, { actionVersion: pin.tag });
  if (!report.ok) {
    throw new AdoptError(
      `emitted workflow failed consumer-controls invariants:\n${formatReport(report)}`,
    );
  }

  const referenceLanguages: ReadonlyArray<Language> = facts.languages.length > 0 ? facts.languages : ["javascript"];
  const referenceFile = layerReference(loadDefaultsReference(targetRepo), {
    languages: referenceLanguages,
    projectName,
  });

  const invariantsReport = formatReport(report);
  const adoptionReport = renderAdoptionReport({
    allowUsers,
    bareAction,
    facts,
    invariantsReport,
    pin,
    projectName,
  });

  const writes: Array<{ content: string; path: string }> = [
    { content: workflow, path: ".github/workflows/codex-review.yaml" },
    { content: referenceFile, path: ".github/codex/review-reference.md" },
    { content: adoptionReport, path: "ADOPTION.md" },
  ];

  if (!dryRun) {
    for (const { content, path } of writes) {
      const abs = resolve(targetRepo, path);
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content);
    }
  }

  return { adoptionReport, invariantsReport, referenceFile, workflow, writes };
}
