import type { Language } from "./detect.js";

const HEADING = /^### ([^(\n]+?)(?:\s*\(`?(.+?)`?\))?$/gm;

const LANG_TO_HEADING: Record<Language, ReadonlyArray<string>> = {
  go: ["Go"],
  java: ["Java / Kotlin"],
  javascript: ["JavaScript / TypeScript"],
  kotlin: ["Java / Kotlin"],
  php: [],
  python: ["Python"],
  ruby: [],
  rust: ["Rust"],
  shell: ["Shell scripts"],
  typescript: ["JavaScript / TypeScript"],
};

const ALWAYS_INCLUDE = ["YAML / Configuration", "Markdown", "Dockerfile / Container"];

export function listSections(reference: string): Array<{ end: number; heading: string; start: number }> {
  const sections: Array<{ end: number; heading: string; start: number }> = [];
  const matches = [...reference.matchAll(HEADING)];
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    if (m === undefined || m[1] === undefined) continue;
    const heading = m[1].trim();
    const start = m.index ?? 0;
    const next = matches[i + 1];
    const end = next === undefined ? reference.length : (next.index ?? reference.length);
    sections.push({ end, heading, start });
  }
  return sections;
}

export function pickSectionsForLanguages(
  reference: string,
  languages: ReadonlyArray<Language>,
): Array<{ end: number; heading: string; start: number }> {
  const wanted = new Set<string>();
  for (const lang of languages) {
    for (const heading of LANG_TO_HEADING[lang] ?? []) wanted.add(heading);
  }
  for (const heading of ALWAYS_INCLUDE) wanted.add(heading);
  return listSections(reference).filter((section) => {
    for (const candidate of wanted) {
      if (section.heading.startsWith(candidate)) return true;
    }
    return false;
  });
}

export type LayerOptions = {
  languages: ReadonlyArray<Language>;
  projectName: string;
};

export function layerReference(defaultsContent: string, opts: LayerOptions): string {
  const sections = pickSectionsForLanguages(defaultsContent, opts.languages);
  const fileTypeBlocks = sections
    .map((section) => defaultsContent.slice(section.start, section.end).trimEnd())
    .join("\n\n");

  const header = [
    `# Review reference — ${opts.projectName}`,
    "",
    "<!--",
    "  Generated by codex-review:adopt. Customize the sections below to fit your repo's review priorities.",
    "  This file is NOT wired into the workflow's `with: review-reference-file:` block by default.",
    "  Workspace-mode reads expose policy edits to PR authors. Wire the file only after either:",
    "  (a) deciding to accept workspace-mode posture for same-repo PRs (document the consent inline), or",
    "  (b) issue #97 lands review-reference-source: base, at which point this default flips.",
    "-->",
    "",
    "## Focus areas",
    "",
    "Evaluate the pull request diff for:",
    "",
    "1. **Correctness** — behavioral bugs, regressions, logic errors",
    "2. **Security** — injection, secret exposure, unsafe input handling",
    "3. **Performance** — unnecessary allocations, O(n^2) where O(n) suffices",
    "4. **Maintainability** — readability, naming, duplication, unnecessary complexity",
    "5. **Test coverage** — risky changes without corresponding tests",
    "",
    "## File-type review guidance",
    "",
    "Apply the appropriate checklist for each file type changed in the diff.",
  ].join("\n");

  return `${header}\n\n${fileTypeBlocks}\n`;
}
